language: scala

sudo: false

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot
    - $HOME/.sbt/launchers

scala:
  - 2.12.7

matrix:
  include:
  - env: SBT_VERSION="0.13.17" EXAMPLE_BUILD="false"
    jdk: oraclejdk8
  - env: SBT_VERSION="1.2.6" EXAMPLE_BUILD="true"
    jdk: oraclejdk8

script:
  - sbt "^^ ${SBT_VERSION}" scripted

  # Check that the example can be compiled.
  - if [[ "${EXAMPLE_BUILD}" == "true" ]]; then
      cd example;
      sbt swaggerMeta;
      cat target/swagger.yml;
    fi

before_cache:
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm

