language: scala

sudo: false

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot
    - $HOME/.sbt/launchers

matrix:
  include:
    - env: SBT_VERSION="0.13.18" EXAMPLE_BUILD="false"
    - env: SBT_VERSION="1.3.3" EXAMPLE_BUILD="true"

script:
  - sbt "^^ ${SBT_VERSION}" scripted

  # Check that the example can be compiled.
  - if [[ "${EXAMPLE_BUILD}" == "true" ]]; then
      cd example;
      sbt swaggerMeta;
      cat target/swagger.yml;
    fi

before_cache:
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm

